### PR TITLE
#34 Updated Readme

### LINKED ISSUE #34: Add PRD in README
Add product description in README file. It will act as our Product Requirements Document (PRD).

A PRD outlines the requirements of what you’re going to build so that people know what the completed product should do. 

PRDs typically include the following:
- Purpose — Who it’s for and why you’re building it.
- Features — What you’re going to build.

## Purpose
-   What problems this product solves.
-   Who will use the product.
-   Why it’s important.

## Features
This step is to determine the feature requirements for the release. Every feature should support the overall purpose of  product.

### PR DESCRIPTION
**Pull request by krishnanvignesh**
Fixes #34 Add PRD in README

- Added Purpose
- Added Feature
- Added Contribution guidelines link
- Added issues link
- Added NGO link

### CODE REVIEW

**Comment by ritesh-pandey** [comment]
We planned to open all development PR against `development` branch, right?
Please correct me if I am wrong.

**Comment by krishnanvignesh** [comment]
> We planned to open all development PR against `development` branch, right?
> Please correct me if I am wrong.

Yes, I have raised this PR against the development branch.

**Comment by ritesh-pandey** [comment]
In PR description, please use format
`Fixes <issue number>`

This was the PR will automatically get tagged with issue.

**Comment by krishnanvignesh** [comment]
> In PR description, please use format
> `Fixes <issue number>`
> `Other description...`
> 
> This was the PR will automatically get tagged with issue.

Done.

**Pull request merged**
